/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTipoOperadores;

public class App {

    public static void main(String[] args) {
        
        String nome = "Daniel";
        int idade = 25;
        float altura = 1.85f;
        double cotacaoDolar = 5.45d;
        char genero = 'M';
        byte pontos = 0;
        boolean sabeProgramar = true;
        
        System.out.print("O " + nome + " tem " + idade + " e possuí " + altura + " de altura!");
        
    }
}
